name: unboton
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4651
title: UnBoton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#241f20'
    - '#00c3b8'
    - '#dfdfe0'
    - '#6ed4d1'
    - '#008080'
  brandStrength: 0.3125
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
