name: unboton
favicon: null
layout_spectrum: 0.7574274437502027
typography_spectrum: 0.46906729228794575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2731980679091066
  lightness: 0.8053174770902842
  saturation: 0.8705430652480572
  rhythmicContrast: 0.8625783226452768
purpose: []
